"""add media.content_sha256 for dedup

Revision ID: 44cd48371b07
Revises: ed1c5595f7aa
Create Date: 2026-04-22 20:27:50.364137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44cd48371b07'
down_revision: Union[str, Sequence[str], None] = 'ed1c5595f7aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('content_sha256', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_media_content_sha256'), 'media', ['content_sha256'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_content_sha256'), table_name='media')
    op.drop_column('media', 'content_sha256')
    # ### end Alembic commands ###
