"""init media and media_segments tables

Revision ID: 70c076c9215e
Revises: 
Create Date: 2026-04-20 20:46:50.785638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '70c076c9215e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_kind', sa.String(length=20), nullable=False),
    sa.Column('original_name', sa.String(), nullable=True),
    sa.Column('stored_path', sa.String(), nullable=True),
    sa.Column('playback_path', sa.String(), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('has_video', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('has_audio', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('score_avg', sa.Integer(), nullable=True),
    sa.Column('score_grade', sa.String(length=4), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_segments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('media_id', sa.String(), nullable=False),
    sa.Column('t_start_ms', sa.Integer(), nullable=False),
    sa.Column('t_end_ms', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('extras', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_segments_media_id'), 'media_segments', ['media_id'], unique=False)
    op.create_index('ix_media_segments_media_id_t_start', 'media_segments', ['media_id', 't_start_ms'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_media_segments_media_id_t_start', table_name='media_segments')
    op.drop_index(op.f('ix_media_segments_media_id'), table_name='media_segments')
    op.drop_table('media_segments')
    op.drop_table('media')
    # ### end Alembic commands ###
